/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulos.sistema.menuprincipal;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modulos.mantenimiento.categoriaplato;
import modulos.mantenimiento.clienteform;
import modulos.mantenimiento.platoform;
import modulos.mantenimiento.usuarioform;

/**
 *
 * @author javie
 */
public class menuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuprincipal
     */
    
    public class Imagen extends javax.swing.JPanel {
 
        public Imagen() {
            this.setSize(300, 400); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics
 
        public void paint(Graphics grafico) {
            Dimension height = getSize();

            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa

            ImageIcon Img = new ImageIcon(getClass().getResource("/assets/img/principal.png")); 

            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel

            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);

            setOpaque(false);
            super.paintComponent(grafico);
        }
    }

    public menuprincipal() {
        initComponents();
        this.setLocationRelativeTo(this);
        Imagen Imagen = new Imagen();
        panelImagen.add(Imagen);
        panelImagen.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiPlato = new javax.swing.JMenuItem();
        jmiCategoriaplato = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema restaurant");
        setPreferredSize(new java.awt.Dimension(1000, 601));

        panelImagen.setBackground(new java.awt.Color(255, 255, 255));
        panelImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelImagen.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setBackground(new java.awt.Color(0, 112, 192));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/ui.png"))); // NOI18N
        jMenu1.setText("MANTENIMIENTO");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmiCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/cliente.png"))); // NOI18N
        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCliente);

        jmiPlato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmiPlato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/comida.png"))); // NOI18N
        jmiPlato.setText("Plato");
        jmiPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPlatoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPlato);

        jmiCategoriaplato.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmiCategoriaplato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/cena.png"))); // NOI18N
        jmiCategoriaplato.setText("Categoria plato");
        jmiCategoriaplato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCategoriaplatoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCategoriaplato);
        jMenu1.add(jSeparator1);

        jmiUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jmiUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/usuario.png"))); // NOI18N
        jmiUsuario.setText("Usuario");
        jmiUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("CONSULTAS");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("PROCESOS");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("REPORTES");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        // TODO add your handling code here:
        new clienteform().setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPlatoActionPerformed
        // TODO add your handling code here:
        new platoform().setVisible(true);
    }//GEN-LAST:event_jmiPlatoActionPerformed

    private void jmiCategoriaplatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCategoriaplatoActionPerformed
        // TODO add your handling code here:
        new categoriaplato().setVisible(true);
    }//GEN-LAST:event_jmiCategoriaplatoActionPerformed

    private void jmiUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUsuarioActionPerformed
        // TODO add your handling code here:
        new usuarioform().setVisible(true);
    }//GEN-LAST:event_jmiUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                }
                new menuprincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem jmiCategoriaplato;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiPlato;
    private javax.swing.JMenuItem jmiUsuario;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
